production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d1eibrdh4fqouj
  username: mfuqsxjfotetap
  password: _LCyhDVWyJ5WKqtQSqnmWH6io_
  host: ec2-54-225-135-30.compute-1.amazonaws.com
  port: 5432